### ISSUE TITLE
yum install twindb-agent fails on CentOS 5

### ISSUE THREAD

**Issue by akuzminsky** [twindb/twindb-agent-testing#4]
In test environment the package is not signed. yum fails to install it.

We need to add `--nogpgcheck` to yum arguments

```
       STDERR: Package twindb-agent-0.2.0-1.noarch.rpm is not signed
       ---- End output of "bash"  "/tmp/chef-script20150919-3580-1hxj1yi" ----
       Ran "bash"  "/tmp/chef-script20150919-3580-1hxj1yi" returned 1
       [2015-09-19T16:59:49+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
-----> Destroying <server55-default-centos-511>...
       ==> default: Forcing shutdown of VM...
       ==> default: Destroying VM and associated drives...
       Vagrant instance <server55-default-centos-511> destroyed.
       Finished destroying <server55-default-centos-511> (0m4.00s).
```

**Comment by ovaistariq** [comment]
It should pass now. Can you test?

On Saturday, September 19, 2015, Aleksandr Kuzminsky <
notifications@github.com> wrote:

> In test environment the package is not signed. yum fails to install it.
>
> We need to add --nogpgcheck to yum arguments
>
>        STDERR: Package twindb-agent-0.2.0-1.noarch.rpm is not signed
>        ---- End output of "bash"  "/tmp/chef-script20150919-3580-1hxj1yi" ----
>        Ran "bash"  "/tmp/chef-script20150919-3580-1hxj1yi" returned 1
>        [2015-09-19T16:59:49+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
> -----> Destroying <server55-default-centos-511>...
>        ==> default: Forcing shutdown of VM...
>        ==> default: Destroying VM and associated drives...
>        Vagrant instance <server55-default-centos-511> destroyed.
>        Finished destroying <server55-default-centos-511> (0m4.00s).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/twindb/twindb-agent-testing/issues/4>.
>


-- 



Ovais Tariq, Lead Reliability Engineer, Lithium
Web: http://www.ovaistariq.net/
Email: me@ovaistariq.net
Skype: ovaistariq
